on: push
name: Sample Workflow

jobs:
  build:
    name: Dev Pr Checker
    runs-on: macos-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3'
          channel: 'stable'
      - run: flutter --version

