on: push
name: Sample Workflow

jobs:
  build:
    name: Dev Pr Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.3'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze .
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart format --set-exit-if-changed

   

