on: push
name: Sample Workflow

jobs:
  build:
    name: Dev Pr Checker
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.3'
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.5.1
        with:
          sdk: 2.19.6
      - run: flutter --version
      - run: flutter pub clean
      - run: flutter pub get
      - run: flutter analyze .
      - run: dart format --set-exit-if-changed

   

