on: push
name: Sample Workflow

jobs:
  build:
    name: Dev Pr Checker
    runs-on: ubuntu-latest
    env:
      MY_APP_ID: ${{ vars.PERCENTAG_COVERAGE }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.4'
      - run: flutter --version
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.5.1
        with:
          sdk: 3.0.3
      - run: dart --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter test --coverage
      - run: dart pub global activate coverde
      # - run: dart format --set-exit-if-changed ### comment muna
      - run: echo "My unknown secret is ${{ env.PERCENTAG_COVERAGE }}"
#      - run: flutter pub run coverde check  Number(String("${PERCENTAG_COVERAGE}"))

   

