on: push
name: Sample Workflow

jobs:
  build:
    name: Dev Pr Checker
    runs-on: macos-latest
    container:
      image:  google/dart:latest
    steps:
      - name: checkout in actions 3
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: prepare flutter in actions 3
        with:
          flutter-version: '3.10.3'
          channel: 'stable'
      - run: flutter --version
      - name: run analyze
      - run: flutter analyze

