on: push
name: Sample Workflow

jobs:
  build:
    name: Dev Pr Checker
    runs-on: ubuntu-latest
    env:
      COVERAGE_CHECK: ${{ vars.PERCENTAG_COVERAGE }}
    steps:
#      - run: echo "My unknown secret is $COVERAGE_CHECK"
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.4'
      - run: flutter --version
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.5.1
        with:
          sdk: 3.0.3
      - run: dart --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter test --coverage
      - run: dart pub global activate coverde
      # - run: dart format --set-exit-if-changed ### comment muna
#      - run: echo "My unknown secret is $MY_APP_ID"
      - run: flutter pub run coverde check $COVERAGE_CHECK
      - run: flutter build apk --debug
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: android APK
          path: build/app/outputs/flutter-apk/app-debug.apk.
          retention-days: 5

   

